### ISSUE TITLE
Testing strategy

### ISSUE THREAD

**Issue by ethagnawl** [danielcompton/clojure-postmark#10]
I was wondering if there's an agreed upon convention for swapping in the postmark-test function when its containing namespace is being used from within an integration test. 

A few approches which spring to mind are:

- Insert conditionals into the containing ns to check against the current environment and import the appropriate function. (I'm not sure if this is even possible.)
- Import both functions into a containing ns and have a wrapper function control which one is used at runtime via a dynamic var. (I believe this is possible, but it feels like a kludge.) 

Any suggestions or insights would be greatly appreciated.

**Comment by danielcompton** [comment]
There's a few more variations I could see here:

1. Dynamically set your postmark API key from environment vars/configuration. Switch between `POSTMARK_API_TEST` and your production API key
2. Have a function/var for `live?`, and switch between using the two different functions at runtime, based on the `live?` value (this is similar to your second option).
3. Use a mocking library to stub this out for you. I'm not familiar with any to recommend, but there is probably something out there that could be helpful?

Sorry I couldn't be more helpful, I haven't really needed to do what you're describing here. When we use postmark in dev, we have a seperate Postmark mail server we use, and we stub out all of the to, cc, bcc addresses to dummy ones (and smuggle them back into the message headers), so we can observe what the real mail would like like going through Postmark.

**Comment by ethagnawl** [comment]
@danielcompton Thanks for the reply. Given that I don't have too much time to devote to this task, I may end up doing something similar to the workflow you've outlined - using a benign email address (e.g. test@example.com) in the test environment. If I do come up with a more robust solution, I'll post a follow-up comment.

**Comment by danielcompton** [comment]
Awesome, I'll close this for now, but feel free to post more comments with your findings.
